timezone: Asia/Hong_Kong
markdown: kramdown
url: https://eric15342335.github.io
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

title: Eric15342335's GitHub Pages \| HKU BASc(AppliedAI) Year 2

author:
  name: Cheng Ho Ming, Eric
  email: eric310@connect.hku.hk
  url: https://eric15342335.github.io/

social:
  name: eric15342335
  links:
    - https://github.com/eric15342335
    - https://www.linkedin.com/in/eric15342335/
    - https://www.instagram.com/ericcheng0310/
    - https://x.com/eric15342335/
    - https://www.binance.com/en/square/profile/eric15342335
    - https://steamcommunity.com/id/eric15342335

twitter:
  username: eric15342335
  card: summary

logo: /assets/images/meguru-big.png

webmaster_verifications:
  google: nKhf3k5Ab3PBY31uGwwA-9csMaoM8j2T96heECb4RuM

feed:
  path: feed.xml
  title: Eric's Blog on GitHub Pages
  description: RSS feed for latest posts on Eric's Blog
  author_name: Cheng Ho Ming, Eric
  author_email: eric310@connect.hku.hk
  author_url: https://eric15342335.github.io/

theme: null
include:
  - .well-known
