timezone: Asia/Hong_Kong
markdown: kramdown
url: https://eric15342335.github.io
plugins:
  - jekyll-feed
  - jekyll-sitemap
feed:
  path: feed.xml
  title: Eric's Blog on GitHub Pages
  description: RSS feed for latest posts on Eric's Blog
  author_name: Cheng Ho Ming, Eric
  author_email: eric310@connect.hku.hk
  author_url: https://eric15342335.github.io/
theme: null
include:
  - .well-known
